name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: x86_64-apple-darwin
        override: true
    - uses: actions-rs/cargo@v1
      with:
        use-cross: true
        command: build
        args: --target x86_64-apple-darwin
    - name: Archive binary
      uses: actions/upload-artifact@v1
      with:
        name: git-fmt_x86_64_apple_darwin.tar.gz
        path: target/release/git-fmt


